# Generated by Django 5.1.5 on 2025-01-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoasPraticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='boas_praticas/')),
                ('conteudo', models.TextField()),
                ('tempo_leitura', models.IntegerField(help_text='Tempo de leitura em minutos')),
                ('link', models.URLField(blank=True, null=True)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='noticias/')),
                ('conteudo', models.TextField()),
                ('tempo_leitura', models.IntegerField(help_text='Tempo de leitura em minutos')),
                ('link', models.URLField(blank=True, null=True)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Painel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('link_painel', models.URLField()),
            ],
        ),
    ]
