# Generated by Django 5.1.5 on 2025-01-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoRapido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('imagem', models.ImageField(upload_to='acesso_rapido/')),
            ],
        ),
    ]
