# Generated by Django 5.1.5 on 2025-01-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publico', '0002_acessorapido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('imagem', models.ImageField(upload_to='banners/')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
