# Generated by Django 5.1.5 on 2025-01-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_alter_processo_camara_alter_processo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='dt_conclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
