# Generated by Django 5.1.5 on 2025-01-24 19:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0003_processo_dt_conclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='data_dist',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
