# Generated by Django 5.1.5 on 2025-01-27 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0005_tarefadodia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='data_dist',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
