# Generated by Django 5.1.5 on 2025-01-31 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0007_comentarioandamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarioandamento',
            name='andamento',
        ),
        migrations.AddField(
            model_name='comentarioandamento',
            name='comentario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='processos.processo'),
            preserve_default=False,
        ),
    ]
