# Generated by Django 5.1.5 on 2025-02-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0009_comentarioprocesso_delete_comentarioandamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='antigo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
