# Generated by Django 5.1.5 on 2025-02-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0010_processo_antigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='numero_processo',
            field=models.CharField(max_length=50),
        ),
    ]
