# Generated by Django 5.1.6 on 2025-02-11 19:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0011_alter_processo_numero_processo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Andamento',
            new_name='ProcessoAndamento',
        ),
    ]
