# Generated by Django 5.1.6 on 2025-02-13 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0012_rename_andamento_processoandamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processoandamento',
            name='fase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.fase', verbose_name='Fase do Processo'),
        ),
    ]
