# Generated by Django 5.1.6 on 2025-02-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0013_alter_processoandamento_fase'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='numero_externo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
