# Generated by Django 5.1.6 on 2025-03-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0014_processo_numero_externo'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='despacho',
            field=models.BooleanField(default=False, verbose_name='É despacho?'),
        ),
        migrations.AddField(
            model_name='processo',
            name='prioridade_urgente',
            field=models.BooleanField(default=False, verbose_name='Prioridade Urgente?'),
        ),
    ]
