# Generated by Django 5.1.6 on 2025-04-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0015_processo_despacho_processo_prioridade_urgente'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='dt_baixa',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
