# Generated by Django 5.2.1 on 2025-06-03 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0017_tema_processo_tema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField()),
                ('semana_fim', models.DateField()),
                ('meta_qtd', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concluida', models.BooleanField(default=False)),
                ('processos', models.ManyToManyField(related_name='metas_semanal', to='processos.processo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_semanal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'semana_inicio', 'semana_fim')},
            },
        ),
    ]
