# Generated by Django 5.2.1 on 2026-02-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0019_objetivo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Objetivo',
        ),
    ]
