# Generated by Django 5.2.1 on 2026-03-24 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0020_delete_objetivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoPauta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=100, verbose_name='Número do Processo')),
                ('data_sessao', models.DateTimeField(verbose_name='Data da Sessão')),
                ('tipo_sessao', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], default='presencial', max_length=20, verbose_name='Tipo de Sessão')),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
                ('processo_vinculado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pautas', to='processos.processo', verbose_name='Processo no Sistema')),
            ],
            options={
                'verbose_name': 'Processo em Pauta',
                'verbose_name_plural': 'Processos em Pauta',
                'ordering': ['data_sessao', 'numero_processo'],
            },
        ),
    ]
