# Generated by Django 5.2.1 on 2026-03-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0021_pauta_sessao'),
    ]

    operations = [
        migrations.AddField(
            model_name='processopauta',
            name='especie_manual',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Espécie (Manual)'),
        ),
        migrations.AddField(
            model_name='processopauta',
            name='link_documento_manual',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Documento (Manual)'),
        ),
        migrations.AddField(
            model_name='processopauta',
            name='responsavel_manual',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Responsável (Manual)'),
        ),
        migrations.AddField(
            model_name='processopauta',
            name='tema_manual',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tema (Manual)'),
        ),
        migrations.AlterField(
            model_name='processopauta',
            name='tipo_sessao',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('vandymara', 'Vandymara'), ('marcio_vidal', 'Márcio Vidal')], default='presencial', max_length=20, verbose_name='Tipo de Sessão'),
        ),
    ]
