# Generated by Django 5.2.1 on 2026-03-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0023_aviso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aviso',
            options={'ordering': ['-fixado', '-criado_em']},
        ),
        migrations.AddField(
            model_name='aviso',
            name='fixado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aviso',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='avisos/'),
        ),
    ]
