# Generated by Django 5.2.1 on 2026-03-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0024_alter_aviso_options_aviso_fixado_aviso_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='avisos/pdfs/'),
        ),
    ]
