# Generated by Django 5.2.1 on 2026-03-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0025_aviso_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processopauta',
            name='tipo_sessao',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('terceira_camara', 'Terceira Câmara'), ('virtual', 'Virtual'), ('vandymara', 'Vandymara'), ('marcio_vidal', 'Márcio Vidal')], default='presencial', max_length=20, verbose_name='Tipo de Sessão'),
        ),
    ]
