# Generated by Django 5.2.1 on 2026-03-31 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0026_alter_processopauta_tipo_sessao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('atendimento', 'Atendimento'), ('geral', 'Agenda Geral')], default='geral', max_length=20, verbose_name='Tipo')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora_inicio', models.TimeField(verbose_name='Horário de Início')),
                ('hora_fim', models.TimeField(blank=True, null=True, verbose_name='Horário de Fim')),
                ('local', models.CharField(blank=True, max_length=200, verbose_name='Local')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('cor', models.CharField(default='#083464', max_length=10, verbose_name='Cor')),
                ('presencial', models.BooleanField(default=True, verbose_name='Presencial?')),
                ('numero_processo', models.CharField(blank=True, max_length=100, verbose_name='Número do Processo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromissos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compromisso',
                'verbose_name_plural': 'Compromissos',
                'ordering': ['data', 'hora_inicio'],
            },
        ),
    ]
