# Generated by Django 5.2.1 on 2026-04-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0027_compromisso'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisso',
            name='cancelado',
            field=models.BooleanField(default=False, verbose_name='Cancelado?'),
        ),
    ]
