# Generated by Django 5.2.1 on 2026-04-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0028_compromisso_cancelado'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisso',
            name='link_reuniao',
            field=models.URLField(blank=True, null=True, verbose_name='Link da Reunião (Teams/Zoom)'),
        ),
    ]
