# Generated by Django 5.2.1 on 2026-04-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0029_compromisso_link_reuniao'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='tags_materia',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Tags de Matéria'),
        ),
    ]
