# Generated by Django 5.2.1 on 2026-04-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0031_ferias_plantoes_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferias',
            name='periodo_aquisicao',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Período de Aquisição'),
        ),
    ]
