# Generated by Django 5.2.1 on 2026-04-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0032_ferias_periodo_aquisicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='processopauta',
            name='link_memorial',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Memorial'),
        ),
    ]
