# Generated by Django 5.1.5 on 2025-01-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='unidade',
            new_name='funcao',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telefone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
