# Generated by Django 5.1.6 on 2025-02-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='jurisprudencia/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelosDecisoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='modelos/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromptConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(default='Você é um assessor de gabinete especializado em liminares de medicamentos, utilize linguagem simples.')),
            ],
        ),
        migrations.DeleteModel(
            name='BaseConhecimentoPDF',
        ),
        migrations.RemoveField(
            model_name='documentoprocesso',
            name='liminar',
        ),
        migrations.AddField(
            model_name='documentoprocesso',
            name='nome',
            field=models.CharField(default='Documento sem nome', max_length=255),
        ),
        migrations.DeleteModel(
            name='Liminar',
        ),
    ]
