# Generated by Django 5.1.6 on 2025-02-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IA', '0002_baseconhecimento_modelosdecisoes_promptconfig_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentoprocesso',
            name='data_upload',
        ),
        migrations.RemoveField(
            model_name='documentoprocesso',
            name='nome',
        ),
    ]
