# Generated by Django 5.1.6 on 2025-02-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IA', '0003_remove_documentoprocesso_data_upload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseconhecimento',
            name='data_upload',
        ),
        migrations.AlterField(
            model_name='baseconhecimento',
            name='arquivo',
            field=models.FileField(upload_to='base_conhecimento/'),
        ),
    ]
